### ISSUE TITLE
Improve IIDM case repository

### ISSUE THREAD

**Issue by mathbagu** [itesla/ipst#17]
IIDM cases are stored in a XML folder (see EntsoeAndXmlCaseRepository class). XML is not a good choice because CIM1 and CGMES are also stored in XML format. Furthermore, in a future release, it could be possible to import IIDM case from a JSON file. The name of the storage folder should be more specific (IIDM for instance).
It could be interesting to store compressed IIDM-XML file instead of plain text file (gzip or bzip2).

**Comment by nomont** [comment]
- Change extension convention: .xml -> .xiidm (x for XML iIDM, because json iIDM will be named .jiidm), but continue to read .xml files for now)
- Add "gz" and/or bzip2 feature: be able to read automatically .xiidm.gz and .xiidm.bz2 (and xml.gz and xml.bz2). There could be both compressed and uncompressed files in the same CaseRepository.
- Change XML to IIDM as the folder name in the EntsoeAndXmlCaseRepository (but continue to support XML folder name when reading a case repository).
