### ISSUE TITLE
Separate format and output file in online tools

### ISSUE THREAD

**Issue by mathbagu** [itesla/ipst#171]
In PR #150 a required "file" parameter has been added to the csv parameters. This feature is not really convenient to use if you want to filter the output for example:
In a previous version we were able to do something like:
```
$> itools print-online-workflow-violations --workflow <id> --csv | grep <filter>
```
In the new version, we need to combine 2 commands:
```
$> itools print-online-workflow-violations --workflow <id> --csv <file>
$> cat <file> | grep <filter>
```

We have to:
- Add a format parameter as a short option: --csv or --ascii (default). 
- Add an optional "--output-file" option with a required parameter. If this option is not set, the tool should print the on the console.
_The code should be evolutive (one day we will maybe add another format)._

The tools to fix are (at least):
- print-online-workflow-violations
- print-online-workflow-postcontingency-violations
- print-online-workflow-postcontingency-loadflow
- print-online-workflow-processing-status
- print-online-workflow-metrics
- print-online-workflow-summary
- print-online-workflow-performances

**Comment by CBiasuzzi** [comment]
two remarks:

1. if the CSV destination is the console, the output could include CSV lines AND log messages; of course it depends on the logger configuration, whether the log is set to go to stdout or a file,  but it is something to be aware of, if you intend to redirect the output to a file or pipe it to other commands

2. I'm not sure that a short parameter (--csv , --ascii) to specify the output format would be a good idea, because both could be used at the same time ... wouldn't it be better a more explicit parameter e.g. --output-format csv|ascii ?

**Comment by mathbagu** [comment]
1. I think we need a "silent" mode on our itools command.It could be manage with a well configured logback XML file. Maybe we can add a "--quiet" option on our tools. (different issue)
2. Agree with your proposal.

For this issue, add the --output-format et --output-file options to the print-online-XXX tools.

**Comment by mathbagu** [comment]
I saw that the print-online-workflow-metrics and the print-online-workflow-performances tools don't use the "table-formatter" configuration. Should I do another issue or could it be managed in this one?

**Comment by CBiasuzzi** [comment]
as for print-online-workflow-performances,  I can manage in this issue;   print-online-workflow-metrics however requires significantly more work:  I guess it'd  deserve a dedicated issue.

**Comment by mathbagu** [comment]
Manage the print-online-workflow-performances and print-online-workflow-metrics in the dedicated issues #179 and #180.
