### ISSUE TITLE
Third party install directory is removed before install step

### ISSUE THREAD

**Issue by mathbagu** [itesla/ipst#18]
Third party install directory is deleted during compilation process if it is a sub-directory of iTesla install directory. To reproduce the behaviour, one can run:
`$> ./install.sh --installDir ~/itesla --thirdpartyDir ~/itesla/thirdparty --wipeInstallDir false`

**Comment by CBiasuzzi** [comment]
I have to ask: 
- installDir contains  the platform compiled binaries (java libraries, executables)
- thirdpartyDir, currently,  contains libraries used by the platfrom at compile time

I wonder why you are trying to put compile time libraries in the installDir ....

**Comment by mathbagu** [comment]
You're right, my test case is not very smart: we don't have to mix runtime binaries and third parties.

But, if I choose to install runtime binaries in a system directory (/usr for instance), the install.sh will try (and succeed) to remove everything in /usr directory. I'm not sure this behaviour is expected.

**Comment by CBiasuzzi** [comment]
true: it would be a bad idea to choose an existing system directory as a target installation (if you are root or have sufficient permissions to write in a system directory, though).
Anyway, I'm going to change the install script so that it will more safely overwrite the existing directories. (instead of removing).  What do you think ?

**Comment by mathbagu** [comment]
Fixed in #26
